### ISSUE TITLE
error in xfce colors

### ISSUE THREAD

**Issue by pjhalsli** [co1ncidence/mountaineer.vim#8]
Just noticed there's an error in the xfce scheme (probably just a typo) - the magenta and cyan bright colorcodes are the same  (the dark theme)

Just thought I'd make you aware

Thanks for Bliss btw - I love the colorscheme

**Comment by co1ncidence** [comment]
Xfce scheme will most likely be remade entirely consider VTE terminals being weird AF, thanks for letting me know about this I will fix it soon.
